Repository GoogleCloudPlatform/cloud-builders, pull requests merged in 2021-03, with the labels that each got.

#758 Update Dockerfile to include local-extract
  gcloud/Dockerfile
Labels: cla: yes, enhancement, feature request

#760 Moving git config above the go.mod check
  go/prepare_workspace.inc
Labels: bug, cla: yes

#764 Pinning Docker version to match current GCB Docker version
  bazel/Dockerfile
  docker/Dockerfile-19.03.8
  docker/cloudbuild.yaml
  javac/Dockerfile
  javac/cloudbuild.yaml
Labels: cla: yes

#763 Pinning Go version to match current GCB Go version
  go/Dockerfile.alpine
  go/Dockerfile.debian
  go/README.md
  go/cloudbuild.yaml
  go/examples/hello_world/Dockerfile
  go/examples/hello_world/cloudbuild.yaml
  go/examples/hello_world/go.mod
  go/examples/hello_world_app/go.mod
  go/examples/https_test/Dockerfile.alpine
  go/examples/https_test/Dockerfile.ubuntu
  go/examples/https_test/cloudbuild.yaml
  go/examples/https_test/go.mod
  go/examples/import_workspace/Dockerfile
  go/examples/import_workspace/cloudbuild.yaml
  go/examples/import_workspace/go.mod
  go/examples/nested_workspace/Dockerfile
  go/examples/nested_workspace/go.mod
  go/examples/whole_workspace/Dockerfile
  go/examples/whole_workspace/cloudbuild.yaml
  go/examples/whole_workspace/go.mod
  go/prepare_workspace.inc
Labels: cla: yes

#767 Assuming "0" when `status` fields are missing from a deployment
  gke-deploy/core/resource/ready.go
  gke-deploy/core/resource/ready_test.go
  gke-deploy/core/resource/testing/deployment-ready-2.yaml
Labels: cla: yes
